language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install --editable .

script: make test

notifications:
  email: false
